// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjkvrjclratsvcsygxum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqa3ZyamNscmF0c3Zjc3lneHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MjA0NjQsImV4cCI6MjA1MzE5NjQ2NH0.0IjN9QUbYkszczOUhqXUx0SRjtXLOwUAnR89t4WWG-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);